// Authentication Types
export const FETCH_LOGGED_IN_USER_SUCCESS = "FETCH_LOGGED_IN_USER_SUCCESS";
export const FETCH_LOGGED_IN_USER_ORDER_HISTORY_SUCCESS =
  "FETCH_LOGGED_IN_USER_ORDER_HISTORY_SUCCESS";
export const FETCH_PRODUCT_INVENTORY =
  "FETCH_PRODUCT_INVENTORY";
